[package]
name = "Lyricly"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.24"
serde = "1.0.228"
serde_json = "1.0.145"
tokio = {version = "1.48.0", features = ["full"]}
urlencoding = "2.1.3"
windows = {version = "0.62.2", features = ["Media_Control", "Foundation"]}
